#coding:utf-8
#2017 05 01
#ding

c_train_path = '/home/jssec/Desktop/html/'
c_test_path = '/home/jssec/Desktop/html/'
c_unlabel_path = ''
lamda = 1.0
T = 0.00
#TopKeywords = 9
TOPN = 1


deleteGroup = ['<!--[\s\S]>*?<\/-->',\
'<!--([\s\S]*?)-->',\
'<\s*script[^>]*>[^<]*<([\s\S]*?)/\s*script\s*>',\
'<\s*style[^>]*>[^<]*<([\s\S]*?)/\s*style\s*>',\
'<\s*a[^>]*>[^<]*<([\s\S]*?)/\s*a\s*>',\
]

deleteSymbol = '[^\d^\w]'

k_expert = { \
'hack' : ['hacking','hacker','hack','hackspace'],
'weapon' : ['bullet','gun','9mm','shell','weapon'],
'porn' : ['sex','girl','girls','sexy','porn'],
'search': ['search','engine'],
'bitcoin': ['bitcoin','btc'],
'Maintenance':['maintenance'],
'market':['sale','btc'],
'card':['card'],
'account':['account'],
'software':['download'],
'communication':['irc'],
}

l_train_keynum = {
'porn':19,
'communication':17, 
'fake':15, 
'IDorEncryptedFileName':8,
'Maintenance':20, 
'hack':19, 
'politics':15, 
'market':20,
'certificate':15,
'electronic_equipment':9,
'tor':19,
'bitcoin':16,
'crime':17,
'statistic':20,
'file_store':19,
'test':12,
'gambling':20,
'email':20,
'bussiness':19,
'yellowPage':20,
'file_share':19,
'search':20,
'game':11,
'freedomofspeech':19,
'account':20,
'login':6,
'card':18,
'software':3,
'science':20,
'weapon':20,
'list':5,
'hosting':20,
'drug':20,
'router':20,
'security':20,
}

l_train = ['porn', 'communication', 'share', 'Maintenance', 'hack', 'politics', 'market', 'certificate', 'electronic_equipment', 'tor', 'bitcoin', 'crime', 'card', 'money', 'test', 'gambling', 'email', 'store', 'yellowPage', 'account', 'freedomofspeech', 'debian', 'identity', 'search', 'weapon', 'list', 'hosting', 'drug', 'security', 'software']

c_train_label_default = {
'http://cmarketsiuhtiix5.onion':['market', 'crime'],
'http://gexauw6b2azvohdm.onion':['drug'],
'http://bitstorenctdwhmo.onion':['electronic_equipment'],
'http://rtnn6i5mhihnrae3.onion':['test'],
'http://iw4xcachep26muba.onion':['hosting'],
'http://254ilofeqckehv4i.onion':['electronic_equipment'],
'http://shadowrnzghb5zhb.onion':['bitcoin'],
'http://tqdh2gq3risdt2l2.onion':['test'],
'http://dumpsmarslfo4h5g.onion':['card'],
'http://oofvttk46u5gletu.onion':['list'],
'http://rocketkk5hhqzlbf.onion':['test'],
'http://cannabi4ewmalq3g.onion':['drug'],
'http://bskoid4l5redrw5m.onion':['communication', 'software'],
'http://casinou2gs2xlkfw.onion':['gambling'],
'http://czt4clbt5fbrencu.onion':['test'],
'http://qn4qfeeslglmwxgb.onion':['freedomofspeech'],
'http://amazoncshbielrwp.onion':['card'],
'http://pnxauh22krzb5xso.onion':['hack'],
'http://anon3vukb6poutg6.onion':['communication'],
'http://5p6s4vkwdapnsiaw.onion':['porn'],
'http://fzqnrlcvhkgbdwx5.onion':['drug'],
'http://thebeast6pwekhvs.onion':['search'],
'http://vefqdlcknb2npgk6.onion':['porn'],
'http://africae3vo64mzux.onion':['porn'],
'http://qigcb4g4xxbh5ho6.onion':['tor'],
'http://eqrvbczir5ua2emd.onion':['identity'],
'http://btcmixxehneseqgz.onion':['bitcoin'],
'http://chatlistea3zbsck.onion':['communication'],
'http://bitblendervrfkzr.onion':['bitcoin'],
'http://f2tfsob4btdpitpi.onion':['software'],
'http://ohusanrieoxsxlmh.onion':['debian'],
'http://poulsensqiv6ocq4.onion':['freedomofspeech'],
'http://lolikaastbgo5dtk.onion':['communication'],
'http://ukpasspprmwaqrsd.onion':['certificate'],
'http://hackarmgq2n2erux.onion':['hack'],
'http://hostie65cxwr4tza.onion':['hosting'],
'http://eon3o2n4tohozwsu.onion':['hosting'],
'http://greenroxwc5po3ab.onion':['identity'],
'http://applesf6emggp2pz.onion':['electronic_equipment'],
'http://45k4h4kei56wiozx.onion':['identity'],
'http://elherbotsiddarol.onion':['market'],
'http://eupillu4np223oxe.onion':['drug'],
'http://torrentzwealmisr.onion':['search'],
'http://felixxxboni3mk4a.onion':['store'],
'http://magicrulesunpaa6.onion':['bitcoin'],
'http://torbox3uiot6wchz.onion':['email'],
'http://ewokqwbnd3wrnbxg.onion':['test'],
'http://sollhs4nbdwwzka2.onion':['hosting'],
'http://22222222aziwzse2.onion':['bitcoin'],
'http://tcqe3dubr6oeq23n.onion':['communication', 'politics', 'freedomofspeech'],
'http://blacknwico2pm2ax.onion':['card'],
'http://222222222g4bgdec.onion':['bitcoin'],
'http://2kka4f23pcxgqkpv.onion':['weapon'],
'http://unp2zfg4vdpdrhgc.onion':['test'],
'http://l6quosmt2ffwphvf.onion':['account'],
'http://d4aik5sbzkdap5up.onion':['test'],
'http://andcorb2cnq4uoi5.onion':['test'],
'http://rougmnvswfsmd4dq.onion':['tor'],
'http://ccpalsto5gglun22.onion':['account'],
'http://hackcanl2o4lvmnv.onion':['hack'],
'http://coincloud25txgdf.onion':['bitcoin'],
'http://epicmarketbbhhmm.onion':['identity'],
'http://mackduck32sc32vs.onion':['identity', 'card'],
'http://kqms3kz6vctilzoe.onion':['hack'],
'http://twbers4hmi6dx65f.onion':['identity'],
'http://iphoneszc52wf6iw.onion':['electronic_equipment'],
'http://fmivsuu2vmubsdhx.onion':['drug'],
'http://refugeepmthkt5wn.onion':['politics'],
'http://4m6omb3gmrmnwzxi.onion':['search'],
'http://vhbbidwvzwhahsrg.onion':['test'],
'http://xdedicvhnguh5s6k.onion':['identity'],
'http://uzpsnetq2lpx6pv6.onion':['money'],
'http://comsearchl2zlnre.onion':['search'],
'http://pvgbzphm622hv4bo.onion':['share'],
'http://h2am5w5ufhvdifrs.onion':['politics', 'share'],
'http://o62qwgqtelzbgp33.onion':['list'],
'http://5rcsq4pvr6qwvg2h.onion':['share'],
'http://n6e64mxbpwglofvs.onion':['test'],
'http://slkushhma4pmfirg.onion':['drug'],
'http://dreamrvfuqrpzn4q.onion':['card'],
'http://omertavzkmsn6tp6.onion':['identity'],
'http://hardblush4fncbgz.onion':['list'],
'http://milworme5c53ldlu.onion':['market'],
'http://3vcqxi2ncgzn5wo3.onion':['identity'],
'http://scihub22266oqcxt.onion':['share'],
'http://tpez4zz5a4civ6ew.onion':['debian', 'software'],
'http://oeioei4qg23lbvew.onion':['yellowPage'],
'http://x3nelbld33llasqv.onion':['list'],
'http://6dtxgqam4crv6rr6.onion':['identity'],
'http://omniildracozuuge.onion':['identity'],
'http://rlfaozz3xxpouhig.onion':['communication'],
'http://xidp5a5k3rlxr5r3.onion':['share'],
'http://nvm5m3haipf2gqbi.onion':['identity'],
'http://43qzvceo6ondd6wt.onion':['identity'],
'http://goblin2xsbqonuv5.onion':['freedomofspeech'],
'http://hkkduic5xpmhw3s6.onion':['hosting'],
'http://4dmavioww6random.onion':['yellowPage'],
'http://sqmqwk54twum6z2z.onion':['identity'],
'http://xe3dkvqezioaixew.onion':['freedomofspeech'],
'http://onionnetrtpkrc4f.onion':['communication'],
'http://greenroomtewvwvn.onion':['identity'],
'http://wcnueib4qrsm544n.onion':['identity', 'communication'],
'http://663wbgqczxp445am.onion':['share'],
'http://awoooowoomkccwbs.onion':['politics'],
'http://zakectglg6r3caz4.onion':['share'],
'http://passporxakpmzurx.onion':['certificate'],
'http://utcomsocmtkxlazp.onion':['crime', 'security'],
'http://r6dzkwtpuf46tfoi.onion':['Maintenance'],
'http://h24wtibkbgc543ck.onion':['card'],
'http://nas6vil3oo2bi3td.onion':['test'],
'http://officegixglfqrzr.onion':['money'],
'http://xqrqbzhii6m6sdrv.onion':['yellowPage'],
'http://doxxtereufvckkiz.onion':['market', 'crime'],
'http://agenttoe2dlvxdei.onion':['hack'],
'http://d3goboxon32grk2l.onion':['share'],
'http://lqdnwwwmaouokzmg.onion':['search'],
'http://pastebinkaav4f5x.onion':['test'],
'http://ll6edwtpfl3zdwoi.onion':['freedomofspeech'],
'http://i2bco6umfcicofor.onion':['market'],
'http://deadcertniishzbg.onion':['certificate'],
'http://zmxzzvcvm6oqvckg.onion':['tor'],
'http://coinpigih6i444lm.onion':['identity', 'bitcoin'],
'http://derpmailod2b4axq.onion':['email'],
'http://smoker32pk4qt3mx.onion':['drug'],
'http://ipadairzbbpb6gas.onion':['electronic_equipment'],
'http://rbaco5flcou46wpd.onion':['search', 'yellowPage'],
'http://cherinesboxss3es.onion':['porn'],
'http://222222223l4p3p3k.onion':['Maintenance'],
'http://cgmcoopwhempo6a5.onion':['identity'],
'http://meshsusrgthwax54.onion':['list'],
'http://zzzzzzzzzzaghsao.onion':['tor'],
'http://dgvdmophvhunawds.onion':['list'],
'http://piratecr44nh3nw4.onion':['hack'],
'http://newsiiwanaduqpre.onion':['Maintenance'],
'http://35flmpspwpnarbos.onion':['electronic_equipment'],
'http://sonuh5glplozcs2m.onion':['identity'],
'http://nichank62kpkrxvg.onion':['porn'],
'http://ow24et3tetp6tvmk.onion':['bitcoin'],
'http://o32qlhlfxbtthszt.onion':['market'],
'http://vbmwh445kf3fs2v4.onion':['freedomofspeech'],
'http://wdnqg3ehh3hvalpe.onion':['software', 'security'],
'http://torlinkbgs6aabns.onion':['yellowPage'],
'http://torbox3gurtwq5tz.onion':['email'],
'http://applesavbbloawcm.onion':['electronic_equipment'],
'http://linksvgkrmdzguvo.onion':['yellowPage'],
'http://ma3lisqktqdlg3t6.onion':['drug'],
'http://dr5aamfveql2b34p.onion':['software'],
'http://dnmavengeradt4vo.onion':['identity'],
'http://alzrgrdvxct6c63z.onion':['software'],
'http://hansamkt2rr6nfg3.onion':['market'],
'http://ipfhnseo4hgfw5mg.onion':['freedomofspeech'],
'http://darklawz22nmqdpu.onion':['security'],
'http://udrciweihl4qe63p.onion':['freedomofspeech'],
'http://cnekwx4kmgztzgxq.onion':['electronic_equipment'],
'http://bbbburnsnx2za2tp.onion':['communication'],
'http://ac6kzts6mauq2gfs.onion':['market'],
'http://fovclovtex32cdwh.onion':['Maintenance'],
'http://22222222bxxurr35.onion':['bitcoin'],
'http://publicibkxahavzc.onion':['search'],
'http://archmail5fanreo5.onion':['identity'],
'http://kmltuigipr23dk3g.onion':['tor'],
'http://en35tuzqmn4lofbk.onion':['certificate'],
'http://shopsat2dotfotbs.onion':['hosting'],
'http://5impf36ke4icbif3.onion':['test'],
'http://qubesosmamapaxpa.onion':['software'],
'http://hostzdcvmuqacom4.onion':['hosting'],
'http://z5tfsnikzulwicxs.onion':['tor'],
'http://theboxmmvl6zg3wi.onion':['communication'],
'http://ccxdnvotswsk2c3f.onion':['card'],
'http://prometh5ommmcm4f.onion':['hosting'],
'http://cleancoikmh6uamc.onion':['bitcoin'],
'http://2222kfuzrdpzp35x.onion':['card'],
'http://omega3gobnipc5pc.onion':['search'],
'http://22222222haocmxli.onion':['bitcoin'],
'http://onionoorcazzotwa.onion':['tor', 'software'],
'http://freedoms6tdzr3w4.onion':['freedomofspeech'],
'http://iww2iqhwxmnbh4qs.onion':['share'],
'http://pedocarz5nuz4fpx.onion':['porn'],
'http://pepaieloghlblocc.onion':['share'],
'http://foggedd3mc4dr2o2.onion':['bitcoin'],
'http://dashwikita46grw5.onion':['test'],
'http://xsold3pvbxt4xblv.onion':['freedomofspeech'],
'http://dtavn4vwaaib4ebh.onion':['test'],
'http://as2teuerq62hn6sz.onion':['list'],
'http://x42kpxgbkfdgbizc.onion':['test'],
'http://dnstatstzgfcalax.onion':['yellowPage'],
'http://matrixtgncbufd2r.onion':['store'],
'http://vrm4frcx3pvg6mz4.onion':['share'],
'http://2x4tmsirlqvqmwdz.onion':['identity'],
'http://druglixdfcb3gda3.onion':['money'],
'http://3rzlwnpkzbkxvv2h.onion':['bitcoin'],
'http://pubdrop4dw6rk3aq.onion':['freedomofspeech'],
'http://armsmhmd4c3hb5xu.onion':['weapon'],
'http://lu4qfnnkbnduxurt.onion':['email', 'communication'],
'http://vxrwsocrkbedkbud.onion':['hosting'],
'http://n2ha26oplph454e6.onion':['yellowPage', 'search'],
'http://politiepcvh42eav.onion':['market'],
'http://coindrk42so2x5fe.onion':['bitcoin'],
'http://dumpstreedhgfndk.onion':['card'],
'http://cartvs55wtzng5v3.onion':['crime'],
'http://animalirgsuecrvn.onion':['porn'],
'http://ftec4org3hcpnoir.onion':['electronic_equipment'],
'http://uuxrei5or65anucg.onion':['list'],
'http://searchuqcwgkruxl.onion':['search'],
'http://ukppq4m2uird2zau.onion':['certificate'],
'http://drugs26ucskmvcef.onion':['market'],
'http://secretsxsrvlpawm.onion':['freedomofspeech'],
'http://tc662rk3wmamw4lg.onion':['communication'],
'http://xiqk652hk4lkdba5.onion':['test'],
'http://penguinsmbshtgmf.onion':['bitcoin'],
'http://eucannapggbtppdd.onion':['drug'],
'http://smokerhv5hlklzh2.onion':['drug'],
'http://tfwdi3izigxllure.onion':['electronic_equipment'],
'http://bitmailendavkbec.onion':['email'],
'http://darkheroesfmmp6n.onion':['identity'],
'http://zuag53c4qgqiw2qr.onion':['test'],
'http://foggeddriztrcar2.onion':['bitcoin'],
'http://fakeids5bps3l6qb.onion':['certificate'],
'http://clockwise3rldkgu.onion':['share'],
'http://bitmixergv5vvbza.onion':['bitcoin'],
'http://freedomsct2bsqtn.onion':['freedomofspeech'],
'http://mx5dwqbkplnhcdzp.onion':['market'],
'http://nucleusoitxmebfx.onion':['identity'],
'http://prometh5th5t5rfd.onion':['hosting'],
'http://kkkkkkkkkk63ava6.onion':['software'],
'http://icocainpsv5u5vat.onion':['drug'],
'http://cukggkk6enbnihte.onion':['test'],
'http://lu6oqe5ovmukachv.onion':['account'],
'http://c6wtpvznm4pk6q5u.onion':['certificate'],
'http://electrumseasvwvw.onion':['bitcoin'],
'http://fakeidskhfik46ux.onion':['certificate'],
'http://pistolcqex2ecr5r.onion':['weapon'],
'http://vt5hknv6sblkgf22.onion':['tor'],
'http://b5tearqs4v4nvbup.onion':['debian'],
'http://pwoahxsi4pvaebev.onion':['market', 'identity'],
'http://lotegcc2kvterwb4.onion':['communication'],
'http://oek4nfanuw4dccid.onion':['list'],
'http://25ffhnaechrbzwf3.onion':['drug'],
'http://xdsa5xcrrrxxxolc.onion':['drug'],
'http://dcdoialeklnkb6fg.onion':['freedomofspeech'],
'http://eb6w5ctgodhchf3p.onion':['search'],
'http://liu4cw4aas5csvpn.onion':['test'],
'http://2dwxhlokkkafulra.onion':['market'],
'http://f2qrazeddramv3za.onion':['hack'],
'http://4php6mnkteaouewp.onion':['card'],
'http://52wdeibt3ivmcapq.onion':['share'],
'http://2ogmrlfzdthnwkez.onion':['hack'],
'http://fogwalletgw4g2nc.onion':['bitcoin'],
'http://stoned3dzzhnoe4r.onion':['drug'],
'http://toristfgqiroaded.onion':['share', 'communication'],
'http://refugeegwsl23t5z.onion':['politics'],
'http://foggeduu2ws5bxk5.onion':['bitcoin'],
'http://pab3vhzwe44uwphp.onion':['drug'],
'http://darknetco4i4prlp.onion':['identity'],
'http://wiki5kauuihowqi5.onion':['Maintenance'],
'http://lockluk3ihwblma4.onion':['bitcoin'],
'http://cwoiopiifrlzcuos.onion':['software', 'security'],
'http://udsmewv45lunzoo4.onion':['yellowPage'],
'http://rechardsp4x6tdrh.onion':['market'],
'http://vendogsxo324bpnz.onion':['account'],
'http://22222222m4cetz5t.onion':['bitcoin'],
'http://a5gvhrpulvq33b3q.onion':['freedomofspeech'],
'http://sqqtd3dprdsp3fzq.onion':['test'],
'http://auutwvpt2zktxwng.onion':['yellowPage'],
'http://counterfn2x4wqga.onion':['money'],
'http://fakebillkelmwaos.onion':['money'],
'http://rkphrici4u5ffhhm.onion':['freedomofspeech'],
'http://amazonx6kqmek453.onion':['card'],
'http://ihacker355hscnhv.onion':['communication', 'account'],
'http://vpuuc5kh34hgvskx.onion':['market'],
'http://5eme2auqilcux2wq.onion':['hack'],
'http://achzkqvsdq5vspx5.onion':['test'],
'http://ms5qd5es5qltiqsf.onion':['freedomofspeech'],
'http://limaconzruthefg4.onion':['drug'],
'http://kzfzhi4nsvzx4rr3.onion':['hack'],
'http://phkttm64gbquasaq.onion':['bitcoin'],
'http://ltvplgp6pimxg3nv.onion':['test'],
'http://rso4hutlefirefqp.onion':['drug'],
'http://o4zilmfs3mtfzo25.onion':['money'],
'http://i4tnv5q55bdps3xz.onion':['freedomofspeech', 'communication'],
'http://tor26itgpdacug4u.onion':['market'],
'http://ihdhoeoovbtgutfm.onion':['list'],
'http://shn3x3whdm5tuut4.onion':['store'],
'http://gmgbxa2nnra6plo3.onion':['test'],
'http://5pu4bdevev3dwoqn.onion':['card'],
'http://servnetshsztndci.onion':['hosting'],
'http://hansamkt3iph6sbb.onion':['market'],
'http://4gsgcfwrtvfagmxu.onion':['test'],
'http://darkdirmpmoq3uur.onion':['yellowPage'],
'http://zmovietoropzaid3.onion':['share'],
'http://xstftgk5c3hnf2s6.onion':['card'],
'http://hss3uro2hsxfogfq.onion':['search'],
'http://4qt45wbulqipigwa.onion':['software', 'security'],
'http://qafprb5zdfstbihb.onion':['identity'],
'http://vendorcugc6oppvb.onion':['card', 'account'],
'http://3mrdrr2gas45q6hp.onion':['identity'],
'http://qza32xuddl3guikc.onion':['security'],
'http://mpq4dnmbrk5cnnmz.onion':['test'],
'http://mc6nld3smffo3vgm.onion':['store'],
'http://bluemoon4vpzulpv.onion':['crime'],
'http://fakepassbxbwcvtk.onion':['certificate'],
'http://blenderri3sud4e6.onion':['bitcoin'],
'http://torc5bhzq6xorhb4.onion':['politics', 'security'],
'http://newpdsuslmzqazvr.onion':['drug'],
'http://expressobutiolem.onion':['hosting'],
'http://qqvbgcu6kohbkxbs.onion':['email'],
'http://escrowaaztmtwzgd.onion':['freedomofspeech'],
'http://ltxocqhw4eruf5lu.onion':['market', 'identity'],
'http://footb6kqariohxcf.onion':['gambling'],
'http://ccarderwkstikdeo.onion':['card'],
'http://foggedgprnvuk4uc.onion':['identity'],
'http://foggedxrlwwrrsvw.onion':['identity'],
'http://6php2xx6vczbmgcr.onion':['porn', 'identity'],
'http://shadowrvzgh4fvzw.onion':['bitcoin'],
'http://fixedlwgc3burzts.onion':['gambling'],
'http://gunsammoaahtpmqs.onion':['weapon'],
'http://blkbooknivr3s36u.onion':['Maintenance'],
'http://korovka32xc3t5cg.onion':['identity'],
'http://mrreph6wof6xgt43.onion':['certificate'],
'http://rkea452tdivg4kbe.onion':['bitcoin'],
'http://creditlwkdnptwla.onion':['card'],
'http://dollarsfn45wiq4f.onion':['money'],
'http://haxedcwi5duu363s.onion':['crime'],
'http://countrfoioed4ckx.onion':['money'],
'http://guttenbdoe4mzk6k.onion':['money'],
'http://drugsqfazpkaitwq.onion':['drug'],
'http://neoanime3ptorvb5.onion':['list'],
'http://cash2btc4no5q4ml.onion':['bitcoin'],
'http://vnioqlbi66xfqkfc.onion':['electronic_equipment'],
'http://cidr6kt4la4slizf.onion':['bitcoin'],
'http://swegunsh343s3drf.onion':['weapon'],
'http://22222222235tlt3z.onion':['bitcoin'],
'http://csxtih62vmohxptm.onion':['porn'],
'http://ubcwdcu6o4dslgb6.onion':['electronic_equipment'],
'http://m3pwzf3vsichzhvh.onion':['hack'],
'http://vp5rhkntohnccxea.onion':['bitcoin'],
'http://darkmambawopntdk.onion':['crime'],
'http://deathvoglm2x2lnh.onion':['crime'],
'http://zndclh5h5zr6fgp3.onion':['bitcoin', 'identity'],
'http://giftcardmzsfdsxq.onion':['card', 'account'],
'http://netflixczh23aicf.onion':['hack'],
'http://darknet55ofrx6fv.onion':['list'],
'http://vanitor4cliswzso.onion':['tor'],
'http://tgirleexw34kdbx6.onion':['porn'],
'http://ukpassp4tbkcuvfg.onion':['certificate'],
'http://s42qgnh4kesd5odo.onion':['search'],
'http://bwbvcvmbpnan6xsd.onion':['market', 'politics', 'security'],
'http://btcmixhnpqlpfacx.onion':['bitcoin'],
'http://bitfogfq5thdc6sl.onion':['identity', 'bitcoin'],
'http://bitfogvlgcefva63.onion':['identity', 'bitcoin'],
'http://foggedtdkaqni3e6.onion':['identity', 'bitcoin'],
'http://foggedp6hmxxap5h.onion':['identity', 'bitcoin'],
'http://btcfog52ol2argnx.onion':['identity', 'bitcoin'],
'http://e5qcqoax4chithot.onion':['tor'],
'http://btcfogtlnuz3u2hx.onion':['identity', 'bitcoin'],
'http://bitfogffkzuli23g.onion':['identity', 'bitcoin'],
'http://btcfogvkw35uwagx.onion':['identity', 'bitcoin'],
'http://bitfogl4acbagdso.onion':['identity', 'bitcoin'],
'http://bitcoinplfnd5ozd.onion':['identity', 'bitcoin'],
'http://mda3nxsigriahnxq.onion':['porn'],
'http://ito66nlgdcpnlliv.onion':['market'],
'http://foggedc6plqacing.onion':['identity', 'bitcoin'],
'http://countermltd42g4x.onion':['money'],
'http://foggedbaben2bugc.onion':['identity', 'bitcoin'],
'http://bitfog4clokwvqge.onion':['identity', 'bitcoin'],
'http://bitfogbfuf3vm6qo.onion':['identity', 'bitcoin'],
'http://rothminr5wgew3f4.onion':['card'],
'http://foggeddoi3qh5m2w.onion':['identity', 'bitcoin'],
'http://bitfog5wqcz336f6.onion':['identity', 'bitcoin'],
'http://bitfoggpltag2dxx.onion':['identity', 'bitcoin'],
'http://bitfogwcxhgpmwxk.onion':['identity', 'bitcoin'],
'http://bitfogfknugctz3u.onion':['identity', 'bitcoin'],
'http://fogged6eotpqchva.onion':['identity', 'bitcoin'],
'http://btcfog63txrsozbg.onion':['identity', 'bitcoin'],
'http://bitfogognw33m3ft.onion':['identity', 'bitcoin'],
'http://bitfog4ne3do26xd.onion':['identity', 'bitcoin'],
'http://foggedk6ovwpwcb4.onion':['identity', 'bitcoin'],
'http://bitfogdp2duatgvf.onion':['identity', 'bitcoin'],
'http://foggedls5zv5ta3t.onion':['identity', 'bitcoin'],
'http://anonsteemnqvfma2.onion':['account'],
'http://fakepas423tdibed.onion':['certificate'],
'http://yermrrzeg4fusqx5.onion':['email'],
'http://y3fpieiezy2sin4a.onion':['money'],
'http://hbetshipq5yhhrsd.onion':['gambling'],
'http://3dbr5t4pygahedms.onion':['account'],
'http://k4btcoezc5tlxyaf.onion':['drug'],
'http://254iloft5cheh2y2.onion':['electronic_equipment'],
'http://fightckxiykml2xu.onion':['identity'],
'http://mobil7rab6nuf7vx.onion':['electronic_equipment'],
'http://duskgytldkxiuqc6.onion':['tor'],
'http://wi7qkxyrdpu5cmvr.onion':['communication', 'freedomofspeech'],
'http://ca7gwy56zrifk2xe.onion':['drug'],
'http://fr6scuhdp5dqvy7d.onion':['test'],
'http://vgnettwin5lyl4yr.onion':['freedomofspeech'],
'http://3kyl4i7bfdgwelmf.onion':['politics', 'security', 'freedomofspeech'],
'http://47au5m4eukoxy2a7.onion':['identity'],
'http://ts4cwattzgsiitv7.onion':['bitcoin'],
'http://dioq2yg3l5ptgpge.onion':['freedomofspeech'],
'http://freedomqbueysrt3.onion':['hosting'],
'http://cvalleyeo5lm7gyr.onion':['card'],
'http://6w2nyvsf77q72ue6.onion':['test'],
'http://searchb5a7tmimez.onion':['search'],
'http://bx26hthu5tk7qedw.onion':['certificate'],
'http://ug2kbu4ek7asgpkp.onion':['test'],
'http://usd4cx7otgnx6wtp.onion':['money'],
'http://575wqy3pdg45pywf.onion':['test'],
'http://mvx7igua26khad3k.onion':['list'],
'http://aewfdl3tyohbcenp.onion':['bitcoin'],
'http://nzh3t2xh2nyqgmgt.onion':['share'],
'http://bryemnetihwcflrs.onion':['bitcoin', 'money'],
'http://vfqnd6mieccqyiit.onion':['certificate'],
'http://5deqglhxcoy3gbx6.onion':['tor', 'security'],
'http://zgfgvob256pffy62.onion':['tor'],
'http://gac5e64yd3rsdk5n.onion':['communication'],
'http://wvb2sc7s6ak5deca.onion':['Maintenance'],
'http://pvdebi65pvgphx73.onion':['identity'],
'http://qappoos46myl2bwq.onion':['electronic_equipment'],
'http://z2wyy3l6luhctsoa.onion':['test'],
'http://atlas777hhh7mcs7.onion':['tor'],
'http://n7kr26tlb545urpo.onion':['security'],
'http://wywg65dio2lhe76z.onion':['weapon'],
'http://dc5gee72qyaayr4d.onion':['electronic_equipment'],
'http://hackharhoaw3yk5q.onion':['hack'],
'http://dgoez4e5amzfyd22.onion':['market', 'weapon'],
'http://6w5vyezrvsce6ntm.onion':['list'],
'http://po47k4agopleagki.onion':['freedomofspeech'],
'http://gkqmy7ioqptiru5o.onion':['list'],
'http://ccccrckysxxm6avu.onion':['card'],
'http://2ulc6nqxtyi5gwzm.onion':['search'],
'http://prduct52yhuu6c3f.onion':['electronic_equipment'],
'http://v6gdwmm7ed4oifvd.onion':['freedomofspeech'],
'http://kbxv2hlsy6phxalo.onion':['drug'],
'http://fbyr455vwvkpzp5k.onion':['bitcoin', 'account', 'money'],
'http://vaultu7dxw5bbg37.onion':['bitcoin', 'identity'],
'http://37327zww2mdb76ie.onion':['software'],
'http://4os63v6lqvlaiyz7.onion':['software', 'security'],
'http://5xgrs443ogbyfoh2.onion':['tor'],
'http://eqnbwy4b4k4lrlq5.onion':['card'],
'http://pmwdzvbyvnmwobk5.onion':['hack', 'communication'],
'http://popfilesxuru7lsr.onion':['share'],
'http://k3dlz7wipzvolxw6.onion':['list'],
'http://tails77na25fl35n.onion':['list'],
'http://c4br2yayzdfcfkae.onion':['freedomofspeech'],
'http://mppegdk6kmrr53p7.onion':['money'],
'http://n572ltkg4nld3bsz.onion':['freedomofspeech'],
'http://fncuwbiisyh6ak3i.onion':['communication'],
'http://tetatl6umgbmtv27.onion':['communication'],
'http://sftpstae662x37t7.onion':['list'],
'http://lqdnpadpys4snom2.onion':['search'],
'http://tghtnwsywvvhromy.onion':['identity'],
'http://wtzufw64nt7cloaq.onion':['test'],
'http://yspwdthzg3tnmpzn.onion':['software'],
'http://hosting6iar5zo7c.onion':['hosting'],
'http://paycardmbg4c4rqo.onion':['identity'],
'http://bpo4ybbs2apk4sk4.onion':['security'],
'http://o6klk2vxlpunyqt6.onion':['money'],
'http://futz4b7tmqzoxnc6.onion':['bitcoin'],
'http://f3gcichubmtzs7mq.onion':['test'],
'http://qdigse2yzvuglcix.onion':['security'],
'http://uphnm2dgilz4dysl.onion':['test'],
'http://irc2p5zrbdk25rdy.onion':['communication'],
'http://dw7rmeivs3g7upze.onion':['card'],
'http://ms3pbazxs7qwb422.onion':['drug'],
'http://cstoreav7i44h2lr.onion':['electronic_equipment'],
'http://torhost3p7quiikq.onion':['hosting'],
'http://secrdrop5wyphb5x.onion':['freedomofspeech'],
'http://syro2eznzea2xbpi.onion':['market'],
'http://whonix4iscgg7zzk.onion':['list'],
'http://tuu66yxvrnn3of7l.onion':['weapon'],
'http://goatsehvcopyc2ex.onion':['porn'],
'http://dmru36nvfgtywx47.onion':['hosting'],
'http://3cpleimu2getp5q7.onion':['software'],
'http://lnys2mg7fpvccnoa.onion':['test'],
'http://usapi6ordn7yl2nx.onion':['certificate'],
'http://writeas7pm7rcdqg.onion':['freedomofspeech'],
'http://qrw3w45sx7niqcpg.onion':['Maintenance'],
'http://cpartywvpihlabsy.onion':['search', 'communication'],
'http://usapass3kbzhszyp.onion':['certificate'],
'http://xfnwyig7olypdq5r.onion':['certificate'],
'http://72kkhupynpkdgevn.onion':['test'],
'http://yourdruhftworzg4.onion':['drug'],
'http://zionshopusn6nopy.onion':['market'],
'http://axcdo2zaeyrpdc6z.onion':['freedomofspeech'],
'http://3expgpdnrrzezf7r.onion':['freedomofspeech'],
'http://zdf4nikyuswdzbt6.onion':['freedomofspeech'],
'http://6cws3rcwn7aom44r.onion':['freedomofspeech'],
'http://nrktipspgpsyoqwo.onion':['freedomofspeech'],
'http://mz33367mcdrcdi7s.onion':['freedomofspeech'],
'http://cxoqh6bd23xa6yiz.onion':['freedomofspeech'],
'http://laundryzlzgnni4n.onion':['bitcoin'],
'http://bryemnekeevtpomb.onion':['money', 'bitcoin'],
'http://drkseidwayn6uc5x.onion':['weapon'],
'http://ccpalym5nu3elh5y.onion':['account'],
'http://blackph5fuiz72bf.onion':['card'],
'http://bigsexzwankdb27a.onion':['porn'],
'http://weapon5cd6o72mny.onion':['weapon', 'market'],
'http://laundrymy244rcwn.onion':['bitcoin'],
'http://buybtcstbl2d3igz.onion':['bitcoin'],
'http://btcmixxihego4qyg.onion':['bitcoin'],
'http://cardsp2g54ybnvpg.onion':['card', 'account'],
'http://carddumpa36spoya.onion':['account'],
'http://loundryslz2venqx.onion':['bitcoin'],
'http://gunsdarkhzyowteb.onion':['weapon'],
'http://mystorew25hgytln.onion':['market'],
'http://gunsdtk47tolcrre.onion':['weapon'],
'http://drugszun7tvsgsaa.onion':['drug'],
'http://mollyworh4524fop.onion':['drug'],
'http://hkisl3373gs67icm.onion':['bitcoin'],
'http://luckp47s6xhz26rn.onion':['weapon'],
'http://grannytnglrvaaf7.onion':['porn'],
'http://mixer6nyvxalc252.onion':['bitcoin'],
'http://dedopedhvmcsxylb.onion':['drug'],
'http://mobileay2syyw6qf.onion':['electronic_equipment'],
'http://clonedc2yqbcs7st.onion':['card'],
'http://platypusxchhwv6z.onion':['account'],
'http://lpholfnvwbukqwye.onion':['identity'],
'http://i3ezlvkoi7fwyood.onion':['identity'],
'http://2ozt7po7llmilroa.onion':['hack'],
'http://zqktlwii7klvpbrm.onion':['test'],
'http://zyklonoacemp2bug.onion':['market'],
'http://mkingdompdzmk7e3.onion':['identity'],
'http://playwy6fqtwygqxr.onion':['gambling'],
'http://ulrn6sryqaifefld.onion':['search'],
'http://facez25qzcuvu2t3.onion':['hack'],
'http://uuecxqc4mtzd7ysv.onion':['drug'],
'http://ibgk7stvp6bov6x6.onion':['share'],
'http://cfwl3urfcsml22hb.onion':['porn'],
'http://garlic7ravilyupx.onion':['tor'],
'http://ftyffwtact6nguwi.onion':['porn'],
'http://x6yrg7vxtofezblq.onion':['porn'],
'http://getbase52kibye6l.onion':['identity'],
'http://premier7pxuw4tcn.onion':['security'],
'http://cthulhuydndd7h3s.onion':['crime'],
'http://pq7yabstfuxw3fwh.onion':['porn'],
'http://ncikv3i4qfzwy2qy.onion':['email', 'tor'],
'http://nixmoneyr4osbyds.onion':['bitcoin'],
'http://h72y5y3tt5lqn64i.onion':['software'],
'http://2pdkdy3eo552mpiz.onion':['software'],
'http://tgssx32xnahbto7b.onion':['card', 'account'],
'http://uts3ozck5w6dpmyg.onion':['card', 'account'],
'http://cardedlxzxsphu5y.onion':['electronic_equipment'],
'http://mqik2n7llhkxuevy.onion':['card'],
'http://exoduockgfq3ikf7.onion':['crime', 'software'],
'http://shyserversmg4gfe.onion':['hosting'],
'http://vhgli4v7feaaz7ka.onion':['politics'],
'http://snuff3pze5un7dbn.onion':['crime'],
'http://foggedyyuowi6nvh.onion':['identity'],
'http://bitblendxpheu7ad.onion':['bitcoin'],
'http://kexh7xtghwmasznr.onion':['list'],
'http://pbbnzshcgemf3d5y.onion':['share'],
'http://5dslbypwo5o4an5k.onion':['politics', 'share'],
'http://2222ppclgy2amp23.onion':['card'],
'http://boyvidscckevqedz.onion':['porn'],
'http://nfkrkvghv75xsf26.onion':['identity'],
'http://rvy6qmlqfstv6rlz.onion':['share'],
'http://vun2ve4khzpnd7ln.onion':['test'],
'http://torprowdd64ytmyk.onion':['tor'],
'http://tewqkyqw7s4vouw2.onion':['identity'],
'http://nywtfc35kvl5oy5g.onion':['test'],
'http://z373bxyt6zhmxepx.onion':['email'],
'http://rb564gvo6isyhayz.onion':['tor', 'software'],
'http://2222kxv6tldvlsn7.onion':['card'],
'http://bettorzztykidrx2.onion':['gambling'],
'http://t36pqdv2ei7pmqa3.onion':['politics'],
'http://rtwtyinmq4wzzl6d.onion':['card'],
'http://3pedopedqayeyvhp.onion':['communication', 'freedomofspeech'],
'http://gtyeo3qebewvp4e6.onion':['share'],
'http://6d6hycywwcshn3hl.onion':['share'],
'http://hdbdah3uhq7ezlnt.onion':['test'],
'http://4nxnu47qd2spvyv2.onion':['store'],
'http://bvildenemxsly33q.onion':['Maintenance'],
'http://fizxfsi3cad3kn7v.onion':['identity'],
'http://76xkbxgntgu2uwxb.onion':['politics'],
'http://n3q7l52nfpm77vnf.onion':['share'],
'http://cerberussssc7cat.onion':['crime', 'software'],
'http://4r23alxe7mwyqa4s.onion':['bitcoin'],
'http://w3hysz3ewytv6efh.onion':['identity'],
'http://tevyc2dds5oxutwe.onion':['identity'],
'http://veiztc7um4piet34.onion':['list'],
'http://bitfogrtf4xzyf23.onion':['identity'],
'http://bbbwtk3u356kadk7.onion':['test'],
'http://on5q7dqzlct7fvef.onion':['test'],
'http://t3tzzluk6it7y3yh.onion':['test'],
'http://z5hns3zhhne7z6bl.onion':['freedomofspeech'],
'http://mwl3znktk7mqogdv.onion':['test'],
'http://anonboy5e4z6vxdl.onion':['identity', 'communication'],
'http://vcmlfg3fgsmy2teu.onion':['identity', 'bitcoin'],
'http://gs7otxifba2ed2yg.onion':['list'],
'http://servertoenof63yc.onion':['list'],
'http://esmmb7ukgz45a63v.onion':['Maintenance'],
'http://2zmcyrryihrpdzka.onion':['Maintenance'],
'http://i7nc6yrshrepr4kn.onion':['test'],
'http://ln6vyadk4hv3dnyt.onion':['store'],
'http://pharmauoq6wnqp7q.onion':['drug'],
'http://2wkwv7m4hetvqo3d.onion':['electronic_equipment'],
'http://5nah6ublcfxdyb6s.onion':['list'],
'http://scryptmaildniwm6.onion':['email'],
'http://btcfogdgpunxyt4b.onion':['bitcoin', 'identity'],
'http://anonymizer5lg2fz.onion':['bitcoin'],
'http://zohaq6hhk2p52c7d.onion':['Maintenance'],
'http://pixxboi756gocop3.onion':['porn', 'identity'],
'http://ays3742ohpasvdoq.onion':['share'],
'http://unlock3cdmwwf6ya.onion':['electronic_equipment'],
'http://blenderylqawcx4g.onion':['bitcoin'],
'http://e4dxlu7v3wcsffp7.onion':['store'],
'http://33oifeg53souby5f.onion':['bitcoin'],
'http://wallet777hk6x7ac.onion':['bitcoin', 'identity'],
'http://ashleymwbwtbwxee.onion':['store'],
'http://dragonso4ito7cal.onion':['test'],
'http://6nefp5kt5yibi25s.onion':['list'],
'http://blender7x5yihbf5.onion':['bitcoin'],
'http://btcfoga5gnae47wd.onion':['identity'],
'http://e5dyelosweg6432w.onion':['share'],
'http://k5rooysqhscw6cuu.onion':['communication'],
'http://fogged7velzqbrzw.onion':['identity', 'bitcoin'],
'http://55uiisia4xo5tyua.onion':['share', 'search'],
'http://milkroad6zwmtbu7.onion':['market', 'card'],
'http://potatooezyf2aql6.onion':['share'],
'http://peachg5g547abn5z.onion':['identity'],
'http://searx7hcqiogbrhk.onion':['search'],
'http://unclesam7nczzyz7.onion':['identity', 'market'],
'http://wrhsa3z4n24yw7e2.onion':['electronic_equipment'],
'http://krkzagd5yo4bvypt.onion':['tor'],
'http://tz4732fxpkehod36.onion':['debian'],
'http://6cd7qka6fo6aps2e.onion':['communication', 'identity'],
'http://zdfsyv3rubuhpql3.onion':['debian'],
'http://hostorx7oztvxnuz.onion':['Maintenance'],
'http://tetatl6xs7bgllvr.onion':['communication'],
'http://oscbw3h7wrfxqi4m.onion':['list', 'debian'],
'http://222246ek6ewyugvf.onion':['bitcoin'],
'http://wcgqzqyfi7a6iu62.onion':['tor'],
'http://grams7euume7rldd.onion':['search'],
'http://typehostrbkz6vwk.onion':['hosting'],
'http://fsocietyiansdaot.onion':['Maintenance'],
'http://fqnqc7zix2wblwex.onion':['software'],
'http://esposgerkgg7nmnx.onion':['share'],
'http://zfu7x4fuagirknhb.onion':['tor'],
'http://57kyoqd5f6u62wz2.onion':['market'],
'http://hz27w5o3zlhptx7v.onion':['software'],
'http://iphone4s36yy7uhh.onion':['electronic_equipment'],
'http://ebxqgaz3dwywcoxl.onion':['list'],
'http://coincloo5wdlx2n7.onion':['bitcoin'],
'http://6nvqpgx7bih375fx.onion':['debian'],
'http://v245twftq76pls6n.onion':['freedomofspeech'],
'http://outforuizcpg7bhy.onion':['market'],
'http://iybwz5aq2yoig7q6.onion':['store', 'software'],
'http://rcw3tpb6kv4hyxuh.onion':['bitcoin'],
'http://zclassica3usf7ra.onion':['bitcoin'],
'http://4kftgyhubzlxvfwi.onion':['politics'],
'http://bryemneh3xycfb6s.onion':['bitcoin', 'money'],
'http://fxigrkvvwzyk46ts.onion':['hosting'],
'http://ynvs3km32u33agwq.onion':['debian'],
'http://chemspain7iw2zby.onion':['drug'],
'http://4glmgsksp7zz3bt7.onion':['card'],
'http://tgel7v4rpcllsrk2.onion':['tor'],
'http://sxrvl46c5v4iviv7.onion':['certificate', 'card'],
'http://k5vbzl3dncboyths.onion':['market'],
'http://rkiwucqgcyv422so.onion':['hosting'],
'http://4hpqiootvyeovr2o.onion':['gambling'],
'http://52g5y5karruvc7bz.onion':['tor'],
'http://tgnv2pssfumdedyw.onion':['tor'],
'http://f7bphdxlqca3sevt.onion':['debian'],
'http://piratecovfmdvt27.onion':['hack'],
'http://nudes2fdd6b775zr.onion':['porn'],
'http://mzrthwhoyxxl66tr.onion':['list'],
'http://sdscoq7snqtznauu.onion':['list'],
'http://r2fklk3x77xr5i4u.onion':['list'],
'http://ammd7ytxcpeavif2.onion':['debian'],
'http://zg5kk7neg3mpulu2.onion':['market'],
'http://payphi6ygg6gncn3.onion':['account'],
'http://icxe4yp32mq6gm6n.onion':['tor'],
'http://ex4gh7cig5ssn2xm.onion':['communication', 'identity'],
'http://tp4ewd72yavuouuy.onion':['certificate'],
'http://idomquol7lannf22.onion':['market'],
'http://e64tunufz7tvbbpt.onion':['test'],
'http://dzyaf4r3usxmzbxg.onion':['list'],
'http://5xxqhn7qbtug7cag.onion':['weapon'],
'http://rqef5a5mebgq46y5.onion':['list'],
'http://mkzx2kkl5v7subvx.onion':['share'],
'http://z373bxyt6zhmxepx.onion:80':['email'],
'http://4pe62vd5g3k22icr.onion':['test'],
'http://tghtnwsywvvhromy.onion:2000':['identity'],
'http://3mrdrr2gas45q6hp.onion:2000':['identity'],
'http://p6vbgbn7ggutkt3i.onion':['freedomofspeech'],
'http://dmys7duszeb2salo.onion':['freedomofspeech'],
'http://gnt3qwmxads3yytg.onion':['list'],
'http://en35tuzqmn4lofbk.onion:80':['certificate'],
'http://hz4dbpmwbnrvxvdk.onion':['test'],
'http://dhostov5qbwwyhcw.onion':['hosting'],
'http://yuvox5mt6nulou72.onion':['bitcoin'],
'http://kaqkiyehzw23pnag.onion':['bitcoin'],
'http://36zbktywbombogys.onion':['porn'],
'http://f5xraa2y2ybtrefz.onion':['identity'],
'http://xcrowbitsqyzvtwf.onion':['hosting'],
'http://tm47kmrvlxuibig7.onion':['hosting'],
'http://blender2tmkocfgs.onion':['bitcoin'],
'http://blenderdewcmwvvy.onion':['bitcoin'],
'http://ruqay5morumo3tcg.onion':['software'],
'http://hackergruemqvew6.onion':['hack'],
'http://fakebillxl6ind2f.onion':['certificate'],
'http://bvk2tenpt6ocegfv.onion':['security', 'yellowPage'],
'http://zenithccenfbee7n.onion':['card'],
'http://wooprzddebtxfhnq.onion':['store'],
'http://u76xgym22s4adf55.onion':['account'],
'http://xd5vfaf2g3t22ckg.onion':['bitcoin'],
'http://zenithcckpsokoga.onion':['card'],
'http://hiddndirxehee3zn.onion':['yellowPage'],
'http://darkwallqxbflfug.onion':['bitcoin'],
'http://fridumprbu2u4iys.onion':['identity'],
'http://unlock26ozqwoyfv.onion':['store'],
'http://22n54hmykxi5bgnu.onion':['list'],
'http://teenxxxbtl7wsllp.onion':['store'],
'http://greendznutpkhdi5.onion':['identity'],
'http://totozzimg6zbvthl.onion':['communication'],
'http://carmlion6vt4az2q.onion':['software', 'tor'],
'http://bulcwbvippdiiqnf.onion':['electronic_equipment'],
'http://gckpt5n5fmlhoaeh.onion':['hosting'],
'http://qmnclhlkbfq35utx.onion':['card'],
'http://scriptsa53voxpsk.onion':['bitcoin'],
'http://alphyzsxv56pcwy3.onion':['card', 'account'],
'http://u4bpvyn6mzvcname.onion':['identity'],
'http://fluesopppwweymod.onion':['market'],
'http://nfu2ufmnln3knn6q.onion':['software', 'security'],
'http://abysmalnsvmnch3y.onion':['test'],
'http://eywr5eubdbbe2laq.onion':['test'],
'http://z7ruaqxmq4fkhy6c.onion':['freedomofspeech'],
'http://adarkfe6a34eqonr.onion':['hosting'],
'http://mqmcsa2fo2m3plua.onion':['test'],
'http://yellow2fqho5h5w6.onion':['test'],
'http://btcdepohyv2c2caa.onion':['bitcoin'],
'http://elysiumqabudewv3.onion':['list'],
'http://greenrowxc57234v.onion':['identity'],
'http://ha4beg7nerydzap4.onion':['electronic_equipment'],
'http://safebtcdllz622bt.onion':['identity'],
'http://marcomacb4ce6dei.onion':['communication', 'identity'],
'http://foggedfpwrdi7zvv.onion':['identity'],
'http://5zf5yc2vwfpoybge.onion':['yellowPage'],
'http://mescuds2uxuaeumk.onion':['bitcoin'],
'http://4twenty2ltimeeop.onion':['drug'],
'http://ponybarn2abkm54u.onion':['hosting'],
'http://dark3dxwtzxnsyvh.onion':['market'],
'http://5mqf5rcfa426nrhk.onion':['hosting'],
'http://vd77m4sb6zwni2eo.onion':['hosting'],
'http://dreamst6a2lekkmv.onion':['identity'],
'http://ubihenecbxmmg6dy.onion':['hosting'],
'http://uytqhgpzit6qmftt.onion':['hosting'],
'http://nlb3hq2qpofi523g.onion':['hosting'],
'http://w3tb3hnz5nv3utr6.onion':['test'],
'http://ws6zodixlh6ln4le.onion':['hosting'],
'http://qbhscvwrq3d5pyiu.onion':['test'],
'http://o6yuuirixtxlxfpc.onion':['card'],
'http://dreamwb6gyu5clrz.onion':['identity'],
'http://coiqlyqfhcm44hsb.onion':['hosting'],
'http://tesemzlxmwalwqbl.onion':['software'],
'http://e34hzf4dsgdsqyki.onion':['hosting'],
'http://6w37evq3wyol5ipy.onion':['hosting'],
'http://bitcoinaovxwbrax.onion':['identity'],
'http://dkrplactwi3a6iod.onion':['hosting'],
'http://bestescros54oblq.onion':['hosting'],
'http://dream36b5z5rpmub.onion':['identity'],
'http://inclibuql666c5c4.onion':['share'],
'http://b7nl3geilvp6e5go.onion':['hosting'],
'http://qs3zumwfci4tntnd.onion':['identity'],
'http://f3s2sam4nvr4rlhm.onion':['hosting'],
'http://dreamrgdtge5xmsl.onion':['identity'],
'http://uvbl4xscbco5hhgv.onion':['test'],
'http://b3m4g5omazyc5cct.onion':['identity'],
'http://dreamt5bnivxu5gt.onion':['identity'],
'http://f6fm6ctuzik7xksd.onion':['hosting'],
'http://pwoah7exkpve56wt.onion':['market', 'identity'],
'http://dreamlskpxbx5caq.onion':['identity'],
'http://yen56cmptivmpgm3.onion':['search'],
'http://fel25g6iq2vvas65.onion':['store'],
'http://dlozslxw2lc3volk.onion':['hosting'],
'http://4famdvaifncy3s5u.onion':['bitcoin'],
'http://dreamnnz4ymemqve.onion':['identity'],
'http://xov5glezk7xt6a22.onion':['hosting'],
'http://22337c6hfefn4tgb.onion':['politics'],
'http://tmt24org5aswzknt.onion':['identity', 'money'],
'http://2t7nmwlzcerkznop.onion':['hosting'],
'http://mssac6bs3ksaqrnv.onion':['hosting'],
'http://kcgs6u33qornxcxv.onion':['identity', 'identity'],
'http://dreambdgui7lur57.onion':['identity'],
'http://sporacmp4poicsme.onion':['card', 'account'],
'http://dreamfaixri3iq73.onion':['identity'],
'http://222222222hsoeiok.onion':['card'],
'http://uklst55vvk2sxfw4.onion':['hosting'],
'http://dream4hwyc5aziew.onion':['identity'],
'http://dreamtc5avruushn.onion':['identity'],
'http://dreambtsek5fiyll.onion':['identity'],
'http://dreamuabfwpwyh4m.onion':['identity'],
'http://hardcore2cfthaqa.onion':['market', 'communication'],
'http://mx75hzo4ptqr7zwz.onion':['hosting'],
'http://k6aumsxzqrpivlme.onion':['hosting'],
'http://kygevwu6ovn34shd.onion':['hosting'],
'http://gxbgmpyn3so3mofi.onion':['hosting'],
'http://hs3fafvd47y3yook.onion':['hosting'],
'http://dreamrv52nvu43gh.onion':['identity'],
'http://rlbiap6nke6tbtw5.onion':['hosting'],
'http://konosuba56er6adh.onion':['tor'],
'http://6s7shony5d4tq4yk.onion':['hosting'],
'http://bqbss75fe2gaen2n.onion':['hosting'],
'http://uxmnei6pwgst4mko.onion':['software'],
'http://oytpxldprxv6tcbk.onion':['bitcoin'],
'http://dreamrlketpmv454.onion':['identity'],
'http://3ks7ghrksllbp2qq.onion':['communication'],
'http://mlvmnxet3dmul5ip.onion':['communication'],
'http://7vxvcumrkdne65k7.onion':['hosting'],
'http://mat23kcc6hwgk3vx.onion':['store'],
'http://mat33phug6lqndps.onion':['store'],
'http://ve2v27hkztfwf6he.onion':['hosting'],
'http://agzoqy5x6v3h6a6x.onion':['hosting'],
'http://waw4anazvaq7e2rp.onion':['bitcoin'],
'http://minecraft5vn35dg.onion':['hosting'],
'http://hvwqpzsodxuab5lr.onion':['hosting'],
'http://6czoihweehqgogv6.onion':['hosting'],
'http://o673q52fplgrucdf.onion':['hosting'],
'http://rvfhyo6vmdcccsim.onion':['hosting'],
'http://dreamzoc2ikgxhqo.onion':['identity'],
'http://dreamrvbpnm6x3q5.onion':['identity'],
'http://fel33logbgiycm5q.onion':['store'],
'http://fuwafuwaqtlkkxwc.onion':['store', 'communication'],
'http://fcc5vph7rbr45fmu.onion':['test'],
'http://dreamwdvw4gum6pe.onion':['identity'],
'http://eavlyseefrrrrrrr.onion':['tor'],
'http://idlucylit6uvimpo.onion':['certificate'],
'http://torstoresohxmqyg.onion':['hosting'],
'http://fel34pd37solhp2p.onion':['store'],
'http://n4ghkapgimsilnlq.onion':['hosting'],
'http://a65l2x472hueax4i.onion':['hosting'],
'http://dreamqvnphv7mg74.onion':['identity'],
'http://vcfg5wwmlizzi4so.onion':['hosting'],
'http://dreamrwtty7umrnx.onion':['identity'],
'http://l2iusbqpwboolmae.onion':['hosting'],
'http://novytitqr2ixsong.onion':['hosting'],
'http://lchudw6xea7xuiip.onion':['identity'],
'http://dreamcprg54atsux.onion':['identity'],
'http://dreamip6hgnvvpkx.onion':['identity'],
'http://e3wa4e24pbkxh4fp.onion':['hosting'],
'http://fel354xtupzhdx7q.onion':['store'],
'http://sn4do42tm2hlnxeh.onion':['software'],
'http://ssqnttmvinyhfson.onion':['hosting'],
'http://5yyk43dzix3q7asc.onion':['test'],
'http://dream7xvxcolnxyc.onion':['identity'],
'http://dreamfrk5xsyoe5o.onion':['identity'],
'http://diamondo36o5zzc4.onion':['drug'],
'http://hykoigfkkatgv4yd.onion':['hosting'],
'http://betfootkvlmv6rge.onion':['gambling'],
'http://dl24pigdetlti6ee.onion':['hosting'],
'http://fel24rc3sssibpal.onion':['store'],
'http://mepaggcyhyq5qu4k.onion':['hosting'],
'http://iqryf7duent53uno.onion':['hosting'],
'http://dreamy5xiqnnnaqf.onion':['identity'],
'http://gv6zipaqcoaau4qe.onion':['share'],
'http://ur5fbg7zlmo3krly.onion':['test'],
'http://wro2ccdk37urufhy.onion':['crime', 'hack', 'money'],
'http://x36ybfxrlzx5pr67.onion':['hosting'],
'http://fel22gpzgvb63pn4.onion':['store'],
'http://kyk55bof3hzdiwrm.onion':['list'],
'http://thuohgpu653omq7w.onion':['hosting'],
'http://lamer2xarhxy72cg.onion':['share'],
'http://dreamd62hbdtk5lz.onion':['identity'],
'http://dqltw5ns66h2kg34.onion':['hosting'],
'http://ytxmrc3pcbv5464e.onion':['share'],
'http://sfioplnt2tr7xttf.onion':['test'],
'http://mqup7t4axdhaycua.onion':['bitcoin'],
'http://dqo3opfk33yzmy2t.onion':['test'],
'http://dreamqms3yv5fzcx.onion':['identity'],
'http://killermsnq2dkogc.onion':['crime'],
'http://swishxyyyhscmmv4.onion':['electronic_equipment'],
'http://canxzwmfihdnn7bz.onion':['communication'],
'http://dreamanqr4adti6p.onion':['identity'],
'http://darkdev5ibekblct.onion':['software', 'store'],
'http://nastypf7kvqdevbo.onion':['porn'],
'http://chaturbov7zh37sa.onion':['communication'],
'http://dreamtx7cvwftyfn.onion':['identity'],
'http://k46wmeoe5pydml6x.onion':['hosting'],
'http://dreamfia57mtgxrh.onion':['identity'],
'http://putlocker4nuslul.onion':['share'],
'http://3qyqgtgudw4rnmqp.onion':['test'],
'http://wicstywyuchnrh4a.onion':['store'],
'http://2i5ki5ueae6mu74u.onion':['hosting'],
'http://torwalkielhk4dxp.onion':['software'],
'http://2e66tonot3xmcbn6.onion':['hosting'],
'http://e2byufqft24mg4wm.onion':['hack'],
'http://yl4kw6oetvyxhar3.onion':['identity'],
'http://dreamatb2o6ts2sw.onion':['identity'],
'http://yey55ssv67hlthld.onion':['identity', 'communication'],
'http://dreamn7slwg2wfnq.onion':['identity'],
'http://cuaorzbto4iq4omt.onion':['hosting'],
'http://ho7zr7kw5omhkvbb.onion':['hosting'],
'http://hack2u5tetwpbug2.onion':['hosting'],
'http://7pbm2tv42hqrrcar.onion':['market'],
'http://73b3h4yqmgaf4spq.onion':['crime'],
'http://tvhmo7uxsu72mwuk.onion':['hosting'],
'http://ifvkuqtklctzc4hz.onion':['hosting'],
'http://mat22s4eohcboc7z.onion':['store'],
'http://brv77pzmamlvq6dq.onion':['Maintenance'],
'http://ladydu6xpzntcfzk.onion':['identity'],
'http://xvultx4llltx7w2d.onion':['identity'],
'http://ircbhe2bgadgllmt.onion':['communication'],
'http://fel23cncdhum7icf.onion':['store'],
'http://bitsqutczza23kgb.onion':['software', 'bitcoin'],
'http://sasake7rmx6ysrmn.onion':['list'],
'http://devuanzuwu3xoqwp.onion':['software'],
'http://mat35lyu3qfqhgvs.onion':['store'],
'http://hsmithsxurybd7uh.onion':['test'],
'http://vinmanebteibui6o.onion':['crime'],
'http://sdd22dkdxdzpp3fg.onion':['bitcoin'],
'http://7rdchbtuldiimax4.onion':['Maintenance'],
'http://e6sid6nazlbp3ezw.onion':['porn'],
'http://qltofas4q3tgnshl.onion':['identity'],
'http://yt7spnudnq2e6tlm.onion':['identity'],
'http://hor6372x6soyyts2.onion':['politics'],
'http://dropoffnegagtvxh.onion':['store'],
'http://torifyumv6emvsop.onion':['hosting'],
'http://mat32scrdvrn5o4m.onion':['store'],
'http://22222frgbeyo3n7v.onion':['porn'],
'http://sqzlgnxfctcfi25q.onion':['drug'],
'http://5r73ozsdvgfgztad.onion':['store'],
'http://v2d6nf2nsvvbgaqe.onion':['freedomofspeech'],
'http://syteogfqpzvw23lk.onion':['drug'],
'http://g46mbrrzpfszonuk.onion':['identity'],
'http://mat26ebbb65svsy3.onion':['store'],
'http://elx57ue5uyfplgva.onion':['share', 'software'],
'http://empereor7ppoy5nn.onion':['drug'],
'http://2cq6qn5svolmanto.onion':['bitcoin'],
'http://kdtvsdxhfc2lwfzg.onion':['bitcoin'],
'http://4a6kzlzytb4ksafk.onion':['bitcoin'],
'http://gotmilk2epf7vova.onion':['drug'],
'http://xsdyzc3xigosczkw.onion':['account'],
'http://5n7y4yihirccftc5.onion':['identity'],
'http://soylentkxgydn6bz.onion':['market'],
'http://youngiwu62nzxna5.onion':['porn'],
'http://hnnmuyz5tcb3u7d4.onion':['identity'],
'http://moldpwdx4r7psgmh.onion':['share', 'market'],
'http://fizxwpbzkn5htzgm.onion':['market'],
'http://nl37dwgoaqkwlmin.onion':['market'],
'http://6prddu4n72tmwk4w.onion':['market'],
'http://eboabtfbnbbebcym.onion':['market'],
'http://bfddkhruniwu2mzm.onion':['software'],
'http://d4qdbfww4f23vz3p.onion':['card'],
'http://c76ve3fd3xsfdfuz.onion':['market'],
'http://rwr2er6bvyitwdza.onion':['market'],
'http://hosting6eun2mouw.onion':['hosting'],
'http://dqeasamlf3jld2kz.onion':['freedomofspeech'],
'http://4hltmu5ywvjivcfe.onion':['security'],
'http://usjudr3c6ez6tesi.onion':['money'],
'http://qx7j2selmom4ioxf.onion':['freedomofspeech'],
'http://3djgibyu5osi4na5.onion':['email'],
'http://onionbr5zulufnuj.onion':['tor'],
'http://q2uftrjiuegl4ped.onion':['identity'],
'http://qkj4drtgvpm7eecl.onion':['money'],
'http://uj3wazyk5u4hnvtk.onion':['search', 'share'],
'http://5i3gqg3jz7zs6x62.onion':['security'],
'http://wikitjerrta4qgz4.onion':['yellowPage'],
'http://y326e4o5ojfnmovx.onion':['identity'],
'http://grams7enufi7jmdl.onion':['search'],
'http://54lnbzjo6xlr4f4j.onion':['tor'],
'http://mail2tor2zyjdctd.onion':['email'],
'http://3m2myjbdihroaven.onion':['Maintenance'],
'http://crypty22ijtotell.onion':['communication'],
'http://4zpinp6gdkjfplhk.onion':['bitcoin'],
'http://shadow7jnzxjkvpz.onion':['politics'],
'http://easycoinsayj7p5l.onion':['bitcoin'],
'http://cryjabkbdljzohnp.onion':['communication'],
'http://twlba5j7oo5g4kj5.onion':['store'],
'http://w5jfqhep2jbypkek.onion':['freedomofspeech'],
'http://giyvshdnojeivkom.onion':['communication'],
'http://walletbjvdecnjgp.onion':['bitcoin'],
'http://xfmro77i3lixucja.onion':['share'],
'http://z2hjm7uhwisw5jm5.onion':['identity'],
'http://grrmailb3fxpjbwm.onion':['email'],
'http://6dvj6v5imhny3anf.onion':['yellowPage', 'communication'],
'http://kaarvixjxfdy2wv2.onion':['search'],
'http://ygzf7uqcusp4ayjs.onion':['tor'],
'http://hackerw6dcplg3ej.onion':['hack'],
'http://btcjaww2avywtadz.onion':['bitcoin'],
'http://ak2uqfavwgmjrvtu.onion':['identity', 'identity', 'freedomofspeech'],
'http://qj3m7wxqk4pfqwob.onion':['communication'],
'http://opnju4nyz7wbypme.onion':['communication'],
'http://q2uftrjiuegl4ped.onion:2000':['identity'],
'http://ic6au7wa3f6naxjq.onion':['software', 'security'],
'http://jq77mc73wz5wuawt.onion':['list'],
'http://w6csjytbrl273che.onion':['freedomofspeech'],
'http://abbujjh5vqtq77wg.onion':['certificate'],
'http://dearsirx6h7j6kro.onion':['bitcoin'],
'http://t4is3dhdc2jd4yhw.onion':['Maintenance'],
'http://jgzvkisiov642jlc.onion':['email'],
'http://rsprjqyxhf25l3qd.onion':['crime', 'hack', 'share'],
'http://wx3wmh767azjjl4v.onion':['identity'],
'http://wx3wmh767azjjl4v.onion:2000':['identity'],
'http://chat7zlxojqcf3nv.onion':['freedomofspeech'],
'http://hpjw636qnt5avq62.onion':['freedomofspeech'],
'http://ll6lardicrvrljvq.onion':['drug'],
'http://ozon3kdtlr6gtzjn.onion':['email', 'identity'],
'http://znig4bc5rlwyj4mz.onion':['freedomofspeech'],
'http://u75jkrt3umu2c7pn.onion':['hosting'],
'http://mixerrzbgcknjzk4.onion':['bitcoin'],
'http://ezuwnhj5j6mtk4xr.onion':['hosting'],
'http://qputrq3ejx42btla.onion':['money', 'account', 'card'],
'http://hacker4hhjvre2qj.onion':['hack'],
'http://jzn5w5pac26sqef4.onion':['account', 'money'],
}


c_test_label_default = {
'http:__vfqnd6mieccqyiit.onion_':['Credit', 'Trading'],
'http:__chatslf537c7qa6k.onion_':['Phones', 'Trading'],
'http:__tt3j2x4k5ycaa5zt.onion_onions.php':['Catalogs'],
'http:__hackcanl2o4lvmnv.onion_hackcanada_hc-faq.html':['Hacking'],
'http:__qzbkwswfv5k2oj5d.onion_':['Forum','Hacking','Market'],
'http:__32pbf32xi6ccm63z.onion_sexymadama_':['Erotic_18+'],
'http:__torvps7kzis5ujfz.onion_index.php_TorVPS':['Hosting'],
#'http:__soupkso3la22ltl3.onion_':['Blog'],
'http:__fncuwbiisyh6ak3i.onion_':['Communication'],
'http:__tochka3evlj3sxdv.onion_marketplace':['Market', 'Trading'],
'http:__tuu66yxvrnn3of7l.onion_':['Weapon', 'Trading'],
'http:__mail2tor2zyjdctd.onion_':['Email'],
'http:__uj3wazyk5u4hnvtk.onion_ ':['File_sharing'],
'https:__blockchainbdgpzk.onion_':['Bitcoin', 'Trading'],
'http:__msydqstlz2kzerdg.onion_':['search_engine'],
'http:__duskgytldkxiuqc6.onion_comsense.html':['Political'],
'http:__qx7j2selmom4ioxf.onion_prices01.htm':['Drug'],
'http:__slwc4j5wkn3yyo5j.onion_':['Trading', 'Financial'],
    }